### ISSUE TITLE
QuickWord fails to launch

### ISSUE THREAD

**Issue by bertelking** [hezral/quickword#16]
I'm using version 2.0.1 from AppCenter. When I click on the launcher, nothing happens. When I tried to launch QuickWord via the terminal, this was the resulting text:

flatpak run com.github.hezral.quickword
Gtk-Message: 13:32:07.529: Failed to load module "canberra-gtk-module"
Quickword 2.0.1
Traceback (most recent call last):
  File "/app/bin/com.github.hezral.quickword", line 24, in <module>
    sys.exit(main.main(VERSION))
  File "/app/share/com.github.hezral.quickword/quickword/main.py", line 127, in main
    app = QuickWordApp()
  File "/app/share/com.github.hezral.quickword/quickword/main.py", line 48, in __init__
    self._word_lookup.get_synsets("a") # hack to load wordnet faster maybe
  File "/app/share/com.github.hezral.quickword/quickword/word_lookup.py", line 63, in get_synsets
    synsets = wn.synsets(word)
  File "/app/lib/python3.8/site-packages/nltk/corpus/util.py", line 121, in __getattr__
    self.__load()
  File "/app/lib/python3.8/site-packages/nltk/corpus/util.py", line 81, in __load
    root = nltk.data.find(f"{self.subdir}/{self.__name}")
  File "/app/lib/python3.8/site-packages/nltk/data.py", line 555, in find
    return find(modified_name, paths)
  File "/app/lib/python3.8/site-packages/nltk/data.py", line 542, in find
    return ZipFilePathPointer(p, zipentry)
  File "/app/lib/python3.8/site-packages/nltk/compat.py", line 41, in _decorator
    return init_func(*args, **kwargs)
  File "/app/lib/python3.8/site-packages/nltk/data.py", line 394, in __init__
    zipfile = OpenOnDemandZipFile(os.path.abspath(zipfile))
  File "/app/lib/python3.8/site-packages/nltk/compat.py", line 41, in _decorator
    return init_func(*args, **kwargs)
  File "/app/lib/python3.8/site-packages/nltk/data.py", line 935, in __init__
    zipfile.ZipFile.__init__(self, filename)
  File "/usr/lib/python3.8/zipfile.py", line 1269, in __init__
    self._RealGetContents()
  File "/usr/lib/python3.8/zipfile.py", line 1336, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file

**Comment by hezral** [comment]
Thanks for reporting this. 
Can you first try to remove this directory and try again? 
~/.var/app/com.github.hezral.quickword

**Comment by bertelking** [comment]
That did it! Though not without some quirks. When I first launched Quickword after deleting the directory, the window opened up blank.
![QuickWord-1](https://user-images.githubusercontent.com/54459077/148975325-b9c5b878-3abf-404c-b2f6-5f0211b36ce8.png)
After waiting a while (maybe 30 seconds, maybe a minute or so), I clicked on the settings cog, and then the prompt to download the dictionary appeared. I don't know if this was coincidental timing or not. 
![QuickWord-2](https://user-images.githubusercontent.com/54459077/148975345-7636fbfc-cb6d-4c7f-81ae-1b8adcdebf88.png)
