### ISSUE TITLE
Won't run

### ISSUE THREAD

**Issue by 4lphanumericusername** [hezral/quickword#7]
It won't open the window if I try launching it with an app, and gives this error when I run it:

```
Traceback (most recent call last):
  File "/usr/bin/com.github.hezral.quickword", line 50, in <module>
    app = application.QuickWordApp()
  File "/usr/share/com.github.hezral.quickword/src/application.py", line 70, in __init__
    self._word_lookup.get_synsets("a")
  File "/usr/share/com.github.hezral.quickword/src/word_lookup.py", line 82, in get_synsets
    synsets = wn.synsets(word)
  File "/usr/lib/python3/dist-packages/nltk/corpus/util.py", line 116, in __getattr__
    self.__load()
  File "/usr/lib/python3/dist-packages/nltk/corpus/util.py", line 78, in __load
    root = nltk.data.find('{}/{}'.format(self.subdir, self.__name))
  File "/usr/lib/python3/dist-packages/nltk/data.py", line 653, in find
    return find(modified_name, paths)
  File "/usr/lib/python3/dist-packages/nltk/data.py", line 639, in find
    return ZipFilePathPointer(p, zipentry)
  File "/usr/lib/python3/dist-packages/nltk/compat.py", line 221, in _decorator
    return init_func(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/nltk/data.py", line 486, in __init__
    zipfile = OpenOnDemandZipFile(os.path.abspath(zipfile))
  File "/usr/lib/python3/dist-packages/nltk/compat.py", line 221, in _decorator
    return init_func(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/nltk/data.py", line 1012, in __init__
    zipfile.ZipFile.__init__(self, filename)
  File "/usr/lib/python3.6/zipfile.py", line 1131, in __init__
    self._RealGetContents()
  File "/usr/lib/python3.6/zipfile.py", line 1198, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file
```

I _did_ accidentally close the window while it was installing wordnet by clicking outside it, but I erased the app and it's dependencies before reinstalling them via various methods to no avail.

**Comment by hezral** [comment]
May i know what install method did you use?

**Comment by 4lphanumericusername** [comment]
Actually, I got the same error on both the setup.py install and AppCenter install. I installed the required packages beforehand for the setup.py install. (you mean python3 and espeak and the other ones, right?)

**Comment by hezral** [comment]
Can you try to remove this folder ~/.local/share/com.github.hezral.quickword as well if you haven't and try again.

**Comment by hezral** [comment]
Any luck getting it to run?

**Comment by vipranarayan14** [comment]
I installed the app thru the elementary AppCenter. I opened the app from Applications, it didn't start. So, I tried to start it from the terminal: `flatpak run com.github.hezral.quickword`. I got the error msg as given below. I uninstalled and reinstalled the app thru the Flatpak cmd line. But got the same error again.

```
Quickword 2.0.1
Traceback (most recent call last):
  File "/app/bin/com.github.hezral.quickword", line 24, in <module>
    sys.exit(main.main(VERSION))
  File "/app/share/com.github.hezral.quickword/quickword/main.py", line 127, in main
    app = QuickWordApp()
  File "/app/share/com.github.hezral.quickword/quickword/main.py", line 48, in __init__
    self._word_lookup.get_synsets("a") # hack to load wordnet faster maybe
  File "/app/share/com.github.hezral.quickword/quickword/word_lookup.py", line 63, in get_synsets
    synsets = wn.synsets(word)
  File "/app/lib/python3.8/site-packages/nltk/corpus/util.py", line 121, in __getattr__
    self.__load()
  File "/app/lib/python3.8/site-packages/nltk/corpus/util.py", line 81, in __load
    root = nltk.data.find(f"{self.subdir}/{self.__name}")
  File "/app/lib/python3.8/site-packages/nltk/data.py", line 555, in find
    return find(modified_name, paths)
  File "/app/lib/python3.8/site-packages/nltk/data.py", line 542, in find
    return ZipFilePathPointer(p, zipentry)
  File "/app/lib/python3.8/site-packages/nltk/compat.py", line 41, in _decorator
    return init_func(*args, **kwargs)
  File "/app/lib/python3.8/site-packages/nltk/data.py", line 394, in __init__
    zipfile = OpenOnDemandZipFile(os.path.abspath(zipfile))
  File "/app/lib/python3.8/site-packages/nltk/compat.py", line 41, in _decorator
    return init_func(*args, **kwargs)
  File "/app/lib/python3.8/site-packages/nltk/data.py", line 935, in __init__
    zipfile.ZipFile.__init__(self, filename)
  File "/usr/lib/python3.8/zipfile.py", line 1269, in __init__
    self._RealGetContents()
  File "/usr/lib/python3.8/zipfile.py", line 1336, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file
```

**Comment by hezral** [comment]
Can you remove ~/.var/app/com.github.hezral.quickwords folder and try again

**Comment by vipranarayan14** [comment]
I did as you said but got the same error again.

1. `rm -rf ~/.var/app/com.github.hezral.quickwords`
2. `flatpak remove com.github.hezral.quickword`
3.  `flatpak install com.github.hezral.quickword`
4. `flatpak run com.github.hezral.quickword`

And 

1. `flatpak remove com.github.hezral.quickword`
2. `rm -rf ~/.var/app/com.github.hezral.quickwords`
3.  `flatpak install com.github.hezral.quickword`
4. `flatpak run com.github.hezral.quickword`

**Comment by hezral** [comment]
can you do flatpak uninstall com.github.hezral.quickword?
your rm -rf has a typo, its quickword not quickwords

I just installed from AppCenter and was able to run it after it downloads the dictionary data.

**Comment by hezral** [comment]
your error log seems to say that the dictionary data is corrupted, maybe the download was interrupted

**Comment by vipranarayan14** [comment]
I have tried installing the app multiple times. Does the app download the dictionary after the installation... in the background?

**Comment by hezral** [comment]
the download only starts when the app is first launch as below. if you remove the ~/.var/app/com.github.hezral.quickword folder, it will reset and show this view again and download again. 

![Screenshot from 2021-11-18 13 11 21](https://user-images.githubusercontent.com/762735/142355807-6c4a041d-7a73-4762-8b7e-7ee436a88637.png)

**Comment by hezral** [comment]
try this, extract this file and move it to ~/.var/app/com.github.hezral.quickword then run the app

[data.zip](https://github.com/hezral/quickword/files/7560103/data.zip)
t

**Comment by vipranarayan14** [comment]
> can you do flatpak uninstall com.github.hezral.quickword? your rm -rf has a typo, its quickword not quickwords
> 
> I just installed from AppCenter and was able to run it after it downloads the dictionary data.

This typo was the problem. (I didn't notice this reply before). I directly went to the directory in file manager and deleted it. Then launched the app and it showed the starting view asking me to download the dictionary. I downloaded the dictionary and **the app is working now.** 

Sorry for the trouble. Thank a lot for the help.

**Comment by hezral** [comment]
glad it worked 😄
